setup:
    pnpm install

format:
    pnpm format

lint:
    pnpm lint

typecheck:
    pnpm typecheck

test:
	pnpm test

dev: all
    pnpm dev

build: all
    pnpm build

preview: all
    pnpm preview

all: setup format lint typecheck test
