services:
  api:
    build:
      context: ..
      dockerfile: api/Dockerfile
    ports:
      - "8000:8000"

  database:
    ports:
      - "5432:5432"

  database-migrate:
    build:
      context: ..
      dockerfile: api/Dockerfile
